import { useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { CategoryChip } from '@/components/finance/CategoryChip';
import { TransactionDateInput } from '@/components/finance/TransactionDateInput';
import { Screen } from '@/components/layout/Screen';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Text } from '@/components/ui/Text';
import { categories } from '@/constants/categories';
import type { TransactionCategory } from '@/types/transaction';
import { useTransactions } from '@/features/transactions/transaction-store';
import { parseTndToMillimes } from '@/lib/parse-money';
export default function AddTransactionScreen() { const router = useRouter(); const { addTransaction } = useTransactions(); const [type, setType] = useState<'income' | 'expense' | undefined>('expense'); const [category, setCategory] = useState<TransactionCategory | undefined>('food'); const [amount, setAmount] = useState(''); const [note, setNote] = useState(''); const [occurredAt, setOccurredAt] = useState(() => new Date()); const [amountError, setAmountError] = useState<string>(); const [formError, setFormError] = useState<string>(); const [isSaving, setIsSaving] = useState(false); const changeType = (nextType: 'income' | 'expense') => { setType(nextType); setFormError(undefined); if (nextType === 'income' && category !== 'salary' && category !== 'other') setCategory('salary'); if (nextType === 'expense' && category === 'salary') setCategory('food'); }; const saveTransaction = async () => { const amountMillimes = parseTndToMillimes(amount); if (!amountMillimes) { setAmountError('Enter an amount with up to three decimal places.'); return; } if (!type || !category) { setFormError('Choose a transaction type and category before saving.'); return; } setIsSaving(true); try { await addTransaction({ type, amountMillimes, category, note, occurredAt: occurredAt.toISOString() }); router.replace('/transactions'); } finally { setIsSaving(false); } }; return <Screen><View style={styles.header}><Text variant="title">Add transaction</Text><Text variant="caption">Saved privately on this device.</Text></View><View style={styles.types}><Button variant={type === 'expense' ? 'danger' : 'secondary'} onPress={() => changeType('expense')}>Expense</Button><Button variant={type === 'income' ? 'primary' : 'secondary'} onPress={() => changeType('income')}>Income</Button></View><Input label="Amount" placeholder="0.000" prefix="TND" keyboardType="decimal-pad" value={amount} onChangeText={(value) => { setAmount(value); setAmountError(undefined); }} error={amountError} /><View style={styles.section}><Text variant="label">CATEGORY</Text><View style={styles.chips}>{categories.filter((item) => type === 'income' ? item.id === 'salary' || item.id === 'other' : item.id !== 'salary').map((item) => <CategoryChip key={item.id} label={item.label} emoji={item.emoji} selected={category === item.id} onPress={() => { setCategory(item.id); setFormError(undefined); }} />)}</View></View>{formError && <Text variant="caption" style={styles.formError}>{formError}</Text>}<TransactionDateInput value={occurredAt} onChange={setOccurredAt} /><Input label="Note (optional)" placeholder="What was this for?" value={note} onChangeText={setNote} /><Button size="lg" loading={isSaving} onPress={() => void saveTransaction()}>Save transaction</Button></Screen>; }
const styles = StyleSheet.create({ header: { gap: 4 }, types: { flexDirection: 'row', gap: 10 }, section: { gap: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, formError: { color: '#DC2626' } });
