import { Alert, Pressable, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Download, HardDriveUpload } from 'lucide-react-native';
import { Screen } from '@/components/layout/Screen';
import { CategoryChip } from '@/components/finance/CategoryChip';
import { TransactionItem } from '@/components/finance/TransactionItem';
import { Card } from '@/components/ui/Card';
import { Text } from '@/components/ui/Text';
import { categories } from '@/constants/categories';
import { formatTransactionDate } from '@/lib/format-date';
import { useTransactions } from '@/features/transactions/transaction-store';
import { colors } from '@/constants/colors';
import { formatMonthYear } from '@/lib/date';
import { EmptyState } from '@/components/ui/EmptyState';
export default function TransactionsScreen() { const router = useRouter(); const { transactions, exportCsv, backupData, isLoading } = useTransactions(); const groupedTransactions = Object.values(transactions.reduce<Record<string, typeof transactions>>((groups, transaction) => { const key = new Date(transaction.occurredAt).toDateString(); groups[key] = [...(groups[key] ?? []), transaction]; return groups; }, {})); const share = async (action: () => Promise<void>) => { try { await action(); } catch (error) { Alert.alert('Export unavailable', error instanceof Error ? error.message : 'Please try again on your device.'); } }; return <Screen><View style={styles.header}><View><Text variant="title">Transactions</Text><Text variant="caption">{formatMonthYear(new Date())} · All accounts</Text></View><View style={styles.headerActions}><ExportAction label="CSV" Icon={Download} onPress={() => void share(exportCsv)} /><ExportAction label="Backup" Icon={HardDriveUpload} onPress={() => void share(backupData)} /></View></View><Text variant="caption">Exports stay on this device until you choose where to share them.</Text><View style={styles.filter}><Text variant="label">FILTER BY CATEGORY</Text><View style={styles.chips}>{categories.slice(0, 5).map((category) => <CategoryChip key={category.id} label={category.label} emoji={category.emoji} />)}</View></View>{isLoading ? <Text variant="caption">Loading your local data…</Text> : transactions.length === 0 ? <EmptyState title="No transactions yet" description="Your local database is ready. Add an expense or income to begin." /> : groupedTransactions.map((group) => <View key={group[0].id} style={styles.group}><Text variant="label">{formatTransactionDate(group[0].occurredAt).toUpperCase()}</Text><Card style={styles.list}>{group.map((transaction) => <Pressable key={transaction.id} accessibilityRole="button" accessibilityLabel={`Edit ${transaction.title}`} onPress={() => router.navigate({ pathname: '/transactions/[id]', params: { id: transaction.id } })} style={({ pressed }) => pressed && styles.transactionPressed}><TransactionItem transaction={transaction} /></Pressable>)}</Card></View>)}</Screen>; }
function ExportAction({ label, Icon, onPress }: { label: string; Icon: typeof Download; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={`Export ${label}`} onPress={onPress} style={({ pressed }) => [styles.exportAction, pressed && styles.pressed]}><Icon size={17} color={colors.primary} /><Text variant="caption" style={styles.exportLabel}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }, headerActions: { flexDirection: 'row', gap: 7 }, exportAction: { minHeight: 42, alignItems: 'center', justifyContent: 'center', gap: 2, paddingHorizontal: 9, borderRadius: 10, backgroundColor: colors.primarySoft }, exportLabel: { fontSize: 11, color: colors.primary, fontWeight: '700' }, pressed: { opacity: .7 }, transactionPressed: { opacity: .65 }, filter: { gap: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, group: { gap: 8 }, list: { paddingVertical: 3 } });
